

vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/dspba_library_package.vhd"                      
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/dspba_library.vhd"                              
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlog -v2k5 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/altera_avalon_sc_fifo.v"                        
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_rtl_core.vhd"                         
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_ast.vhd"                              
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil.vhd"                                  
vcom       "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_tb.vhd"                               
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/dspba_library_package.vhd"                      
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/dspba_library.vhd"                              
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlog -v2k5 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/altera_avalon_sc_fifo.v"                        
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_rtl_core.vhd"                         
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_ast.vhd"                              
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48.vhd"                                  
vcom       "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_tb.vhd"                               
