

ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/dspba_library_package.vhd"                      
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/dspba_library.vhd"                              
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_math_pkg_hpfir.vhd"                   
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/auk_dspip_roundsat_hpfir.vhd"                   
ncvlog      "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/altera_avalon_sc_fifo.v"                        
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_rtl_core.vhd"                         
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_ast.vhd"                              
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil.vhd"                                  
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/tryingfil_sim/tryingfil_tb.vhd"                               
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/dspba_library_package.vhd"                      
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/dspba_library.vhd"                              
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_math_pkg_hpfir.vhd"                   
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/auk_dspip_roundsat_hpfir.vhd"                   
ncvlog      "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/altera_avalon_sc_fifo.v"                        
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_rtl_core.vhd"                         
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_ast.vhd"                              
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48.vhd"                                  
ncvhdl -v93 "C:/repos/fpga_dsp/audio_sdram/filter_48_sim/filter_48_tb.vhd"                               
